### ISSUE TITLE
Restore NFF internal-memory headroom without weakening readiness checks

### ISSUE THREAD

**Issue by pcesar22** [pcesar22/domes#198]
## Specification revision

3b62a6c82160d0271b276bb42894e3d3bb69761e

## Parent objective

Restore a defensible NFF runtime-memory baseline as the first software package in the user-approved dual-NFF lane. This package authorizes software implementation, builds, a PR and CI repair, not device access. Human approval and merge remain mandatory.

## Goal

Attribute the sustained internal-memory shortfall on the physical NFF profile and implement one bounded, regression-tested repair candidate without weakening memory floors or peripheral behavior.

## Non-goals

- Any serial/BLE/device access, flashing, OTA, rollback injection, load campaign or physical acceptance.
- Lowering the 30 KiB firmware self-test/OTA floor or 16 KiB CLI health floor, suppressing tests, shrinking stacks without measured safety evidence, or changing protocol/partitions.
- Scope expansion into the historical first-boot timing repair in issue #106, dependency/controller/skill changes, releases, approvals or merges.

## Required behavior

Start from exact main 3b62a6c. The September 5 retained two-NFF campaign freshly built ESP-IDF v5.4.4 NFF firmware and independently queried both boards. Both pass health but fail only Heap (9/10 self-tests); the untouched second board had the same failure before flashing. Stable retained samples show 322571 B internal-capability total, 23331 B free, 18259 B minimum and 7680 B largest block: free memory is 7389 B below the unchanged 30720 B floor. Application SHA256 ce924e2f54625fe00a3aa3102b06ff03291a0e6a9c887ad883e97f462358ac42; ELF SHA256 2714d986ebbcd46e9b05e9c8f3b39620737069f2d1cb989e9c711c00c56ccbab. Evidence is a historical input, not a new worker measurement.

Quantify relevant static, task-stack and bounded runtime allocations. A source audit identifies a 32000 B tone buffer allocated at audio-task startup before the enable check, a 96 KiB trace ring and a 4096 B profiler stack as investigation candidates, NOT a proven cause. Choose and justify the smallest safe repair. Account for allocator capabilities, DMA/copy requirements, task ownership, allocation failure and fragmentation. Keep audio/trace semantics and timing bounded. Merely deferring a large allocation until the self-test enables TRIAGE/audio is not restored readiness. Never move ISR/cache-critical memory to PSRAM by assumption.

## Acceptance checks

- Retain an allocation attribution and before/after design accounting tied to exact source/profile, separating measured inputs from static analysis and hypotheses.
- Regression tests exercise the chosen buffer/allocation lifecycle, bounded generation or copying, error handling and unchanged functional behavior.
- Preserve both memory thresholds and existing self-test/OTA protection. No capability may be disabled simply to make the readiness test pass.
- Build a fresh isolated physical-NFF image with ESP-IDF v5.4.4 and isolated SDKCONFIG; retain binary/ELF/config identity and size evidence, never reuse ignored sdkconfig/build output.
- Run relevant host firmware tests and required exact-head CI; disclose unavailable checks rather than asserting a pass.
- Publish one review-ready PR with an explicit remaining physical check: separately authorized reflash and complete readiness on both NFFs, including peripheral-active self-test and stable post-test headroom. Do not claim that physical exit from build/static evidence.

## Allowed architectural surfaces

- firmware/domes/main/services/audioService.hpp
- firmware/domes/main/drivers/audioDriver.cpp
- firmware/domes/main/drivers/audioDriver.hpp
- firmware/domes/main/infra/memoryProfiler.cpp
- firmware/domes/main/infra/memoryProfiler.hpp
- firmware/domes/main/main.cpp
- firmware/test_app/CMakeLists.txt
- firmware/test_app/main/test_audio*.cpp
- firmware/test_app/main/test_memory*.cpp
- docs/plans/nff-internal-memory-repair.md

## Dependencies

None

## Required proof

Exact-head allocation rationale, focused regression test results, fresh pinned NFF build provenance, unchanged threshold evidence and required CI links. If a safe repair needs other architectural surfaces, return the specific scope blocker; do not weaken acceptance. Link issue #106 as related history, not an assumed dependency or duplicate closure.

## Hardware operations

None

## Hardware boards

None

## Pull request base

main

## Existing pull request

200

## Work package

NFF-MEM-001

## Work class

software

## Autonomy policy

review-only

**Comment by pcesar22** [comment]
Agent control-plane transition (worker)

Worker returned commit `876fdd8b40f22175341671bff1d303d956376ebf` and 8 verification record(s); blockers: 0.

Specification revision: `3b62a6c82160d0271b276bb42894e3d3bb69761e`
Raw session output is intentionally excluded.

<details><summary>Schema-validated handoff</summary>

```json
{
  "blockers": [],
  "commit": "876fdd8b40f22175341671bff1d303d956376ebf",
  "issue": 198,
  "proposed_followups": [
    "After exact-head CI and independent safety review, dispatch a hardware verifier for the immutable commit on both NFF boards.",
    "Keep issue #106 as related history only; this pull request does not implement or close its first-boot timing work."
  ],
  "pull_request": 200,
  "spec_revision": "3b62a6c82160d0271b276bb42894e3d3bb69761e",
  "state": "agent_review",
  "verification": [
    {
      "artifact": "6/6 tests passed",
      "command_or_observation": "Focused audio allocation-lifecycle regression tests: ctest --test-dir firmware/test_app/build --output-on-failure -R 'audio tone writer'",
      "level": "automated",
      "status": "passed"
    },
    {
      "artifact": "339/339 tests passed",
      "command_or_observation": "Full host firmware suite: ctest --test-dir firmware/test_app/build --output-on-failure",
      "level": "automated",
      "status": "passed"
    },
    {
      "artifact": "domes.bin SHA256 d1e1bc5af9feb30f1920ddf670760fe4bbaee6eef22ef23d2d6fdee0ecad9254; ELF SHA256 52ba9d2479ab6a22a7b7d72d5cb5eba8b0bbd3727edecd8473de472efbd52087; SDKCONFIG SHA256 5b26571b1387b69ab0610462b58e928883c8c21ba5998a541db4e2bec2a9bf17",
      "command_or_observation": "Fresh isolated physical-NFF build with ESP-IDF v5.4.4 and isolated SDKCONFIG: idf.py build size",
      "level": "automated",
      "status": "passed"
    },
    {
      "artifact": "All policy hooks passed under the documented protected read-only .codex EOF-hook exception; no modifications remained",
      "command_or_observation": "pre-commit run --all-files, followed by every non-EOF hook over the full tree and EOF fixer over all changed files",
      "level": "automated",
      "status": "passed"
    },
    {
      "artifact": "origin/codex/issue-198 equals 876fdd8b40f22175341671bff1d303d956376ebf and descends from 3b62a6c82160d0271b276bb42894e3d3bb69761e",
      "command_or_observation": "Remote-head and ancestry confirmation",
      "level": "automated",
      "status": "passed"
    },
    {
      "artifact": "https://github.com/pcesar22/domes/pull/200/checks",
      "command_or_observation": "Controller-owned exact-head CI",
      "level": "automated",
      "status": "pending"
    },
    {
      "artifact": null,
      "command_or_observation": "Device commands were excluded by the task envelope",
      "level": "accepted_command",
      "status": "not_applicable"
    },
    {
      "artifact": null,
      "command_or_observation": "Separately authorized reflash and complete readiness verification on both NFFs, including peripheral-active self-test and stable post-test headroom",
      "level": "physical",
      "status": "pending"
    }
  ]
}
```

</details>

**Comment by pcesar22** [comment]
## Coordinator evidence reconciliation — request independent review, not acceptance

The first worker returned PR #200 at exact head `876fdd8b40f22175341671bff1d303d956376ebf` based on `main` / specification `3b62a6c82160d0271b276bb42894e3d3bb69761e`. I independently confirmed the remote PR identity, head, base and allowed five-file scope.

The immediate `agent:rework` transition came from the worker evidence rule, not a judge verdict. The retained handoff has no failed records or blockers; its two pending records are:

1. Exact-head CI: all eight checks, including CI Gate, now pass on the exact head above (queried from the commit check-runs endpoint on September 5).
2. Physical reflash/readiness: explicitly excluded from this software-only contract and correctly still unverified. This remains a separate future authorized operation. It must not be performed or asserted complete to satisfy this software ticket.

The coordinator is routing the existing artifact to a fresh independent judge. This does not approve the software, alter the original acceptance criteria, erase the handoff, change memory thresholds, authorize a device operation or advance a product milestone. The judge must assess allocation attribution, concurrency, bounded audio behavior, lifecycle/error tests, fresh ESP-IDF build provenance and the exact diff against the original contract. Reject any substantive deficiency. Physical NFF readiness remains 0/2 on the prior measured baseline.

The ticket's Existing pull request field is now #200; repairs must use that PR. There are six open PRs including activation #202: no additional PR capacity is available. The controller's manual-mode CI/PR-cap limitations remain in force.

**Comment by pcesar22** [comment]
Agent control-plane transition (judge)

Independent judge verdict: **reject**; criteria reviewed: 7; required rework items: 1.

Specification revision: `3b62a6c82160d0271b276bb42894e3d3bb69761e`
Raw session output is intentionally excluded.

<details><summary>Schema-validated handoff</summary>

```json
{
  "claim_boundary": "This rejects an evidence-retention deficiency, not the bounded source repair itself. Pending controller-owned exact-head CI was not treated as an implementation criterion or defect. No device access was authorized or performed, so the implementation does not establish physical readiness, peripheral-active behavior, or post-test heap headroom on either NFF.",
  "commit": "876fdd8b40f22175341671bff1d303d956376ebf",
  "criteria": [
    {
      "criterion": "Exact pinned base, artifact identity, and allowed scope",
      "evidence": [
        "Commit 876fdd8b40f22175341671bff1d303d956376ebf has merge-base 3b62a6c82160d0271b276bb42894e3d3bb69761e and is the sole commit above that revision.",
        "The diff changes only five ticket-authorized surfaces: the audio service and driver headers, host-test CMake and audio tests, and the NFF repair plan.",
        "The local branch and origin/codex/issue-198 both resolve to the reviewed commit."
      ],
      "status": "met"
    },
    {
      "criterion": "Allocation attribution and before/after design accounting",
      "evidence": [
        "docs/plans/nff-internal-memory-repair.md separates the September 5 historical measurements from source analysis and prediction.",
        "The plan accounts for the 32000-byte internal tone allocation, 4096-byte audio and profiler stacks, I2S DMA storage, 512-byte scaling scratch, 98304-byte trace request, retained trace pointer table, and 608-byte profiler samples.",
        "The selected repair replaces the persistent 32000-byte internal allocation with a 512-byte static service-owned buffer, predicting a 31488-byte reduction without attributing unmeasured trace placement as proven cause."
      ],
      "status": "met"
    },
    {
      "criterion": "Allocator capabilities, ownership, failure, fragmentation, and bounded timing",
      "evidence": [
        "AudioToneWriter uses a fixed 256-sample member buffer with no runtime allocation, one audio-task owner, and no ISR access.",
        "IAudioDriver::write is synchronous with respect to source-buffer reuse, while Max98357aDriver copies and scales into its driver-local buffer before the underlying I2S write returns.",
        "Tone generation remains capped at 16000 samples and 63 writes; driver errors propagate and successful partial writes return ESP_FAIL.",
        "Trace capacity, task stacks, driver start/stop ordering, asset playback, and the existing 50 ms settling delay are unchanged."
      ],
      "status": "met"
    },
    {
      "criterion": "Regression coverage for lifecycle, bounds, copying, errors, and functional behavior",
      "evidence": [
        "test_audio_driver.cpp covers the 512-byte chunk bound, complete one-second output, 63-write bound, duration capping, short-tone behavior, cross-chunk waveform equivalence, driver-error propagation, and partial-write rejection.",
        "The evidence handoff reports 6/6 focused audio tone-writer tests and 339/339 full host firmware tests passed."
      ],
      "status": "met"
    },
    {
      "criterion": "Readiness thresholds and peripheral behavior remain protected",
      "evidence": [
        "The reviewed diff does not change the firmware 30 KiB internal-capability self-test/OTA floor or the CLI 16 KiB health floor.",
        "No feature, peripheral, protocol, partition, trace capacity, or readiness check is disabled or weakened."
      ],
      "status": "met"
    },
    {
      "criterion": "Fresh isolated ESP-IDF v5.4.4 physical-NFF build identity and retained size evidence",
      "evidence": [
        "The handoff reports a fresh isolated ESP-IDF v5.4.4 build and retains domes.bin SHA256 d1e1bc5af9feb30f1920ddf670760fe4bbaee6eef22ef23d2d6fdee0ecad9254, ELF SHA256 52ba9d2479ab6a22a7b7d72d5cb5eba8b0bbd3727edecd8473de472efbd52087, and SDKCONFIG SHA256 5b26571b1387b69ab0610462b58e928883c8c21ba5998a541db4e2bec2a9bf17.",
        "Neither the schema-validated handoff nor a retained issue-198 repository artifact contains the actual idf.py size output or numerical binary/segment size evidence required by the ticket. Naming `idf.py build size` as the command does not retain its size result."
      ],
      "status": "not_met"
    },
    {
      "criterion": "Review-ready PR and physical-evidence boundary",
      "evidence": [
        "The handoff identifies pull request 200 for the exact reviewed commit.",
        "The committed repair plan explicitly leaves separately authorized reflash and complete readiness verification on both NFFs pending, including peripheral-active self-test and stable current, minimum, and largest-block headroom.",
        "The plan treats issue #106 as related history only and makes no physical-exit claim."
      ],
      "status": "met"
    }
  ],
  "issue": 198,
  "pull_request": 200,
  "required_rework": [
    "Retain the exact-head fresh NFF build's numerical `idf.py size` output or equivalent segment and image-size report in the schema evidence or a reviewable retained artifact, tied to the reported binary, ELF, SDKCONFIG hashes, ESP-IDF v5.4.4, and isolated SDKCONFIG provenance."
  ],
  "spec_revision": "3b62a6c82160d0271b276bb42894e3d3bb69761e",
  "verdict": "reject"
}
```

</details>

**Comment by pcesar22** [comment]
Agent control-plane transition (worker)

Worker returned commit `876fdd8b40f22175341671bff1d303d956376ebf` and 8 verification record(s); blockers: 0.

Specification revision: `3b62a6c82160d0271b276bb42894e3d3bb69761e`
Raw session output is intentionally excluded.

<details><summary>Schema-validated handoff</summary>

```json
{
  "blockers": [],
  "commit": "876fdd8b40f22175341671bff1d303d956376ebf",
  "issue": 198,
  "proposed_followups": [
    "Controller reruns and evaluates exact-head CI for PR #200.",
    "After independent safety review and separate authorization, a hardware verifier exercises immutable commit 876fdd8b40f22175341671bff1d303d956376ebf on both NFF boards."
  ],
  "pull_request": 200,
  "spec_revision": "3b62a6c82160d0271b276bb42894e3d3bb69761e",
  "state": "agent_review",
  "verification": [
    {
      "artifact": "https://github.com/pcesar22/domes/pull/200",
      "command_or_observation": "Fresh isolated physical_nff build: ESP-IDF v5.4.4; `idf.py -C firmware/domes -B .tmp/issue-198-size-rework/build -D IDF_TARGET=esp32s3 -D SDKCONFIG=.tmp/issue-198-size-rework/sdkconfig build size`. DIRAM: 205747/341760 B used, 136013 B remaining. IRAM: 16383/16384 B used, 1 B remaining. Image: 1486004 B before padding; domes.bin: 1486128 B; smallest app partition: 1966080 B with 480976 B free. PR #200 retains these numerical results.",
      "level": "automated",
      "status": "passed"
    },
    {
      "artifact": "https://github.com/pcesar22/domes/pull/200",
      "command_or_observation": "Fresh exact-head identities: domes.bin SHA256 8837169017c7a9b032c8e3bdb6fb130ee26116ddae4749db3edeae28811d3e24; domes.elf SHA256 8d217dbed8f1993e78d7787b9c9078775306c489d2f46e7592a7f55d5f47a0fd; isolated SDKCONFIG SHA256 5b26571b1387b69ab0610462b58e928883c8c21ba5998a541db4e2bec2a9bf17. Generated fidelity manifest identifies profile physical_nff.",
      "level": "automated",
      "status": "passed"
    },
    {
      "artifact": "339/339 host firmware tests passed, including the six audio tone-writer lifecycle regressions.",
      "command_or_observation": "`cmake -S firmware/test_app -B .tmp/issue-198-host-tests && cmake --build .tmp/issue-198-host-tests --parallel && ctest --test-dir .tmp/issue-198-host-tests --output-on-failure`",
      "level": "automated",
      "status": "passed"
    },
    {
      "artifact": null,
      "command_or_observation": "`pre-commit run --all-files`; every hook except EOF fixer passed over the full tree. EOF fixer could not open protected read-only `.codex` files, then passed all five changed files without modifications as required by the sandbox exception.",
      "level": "automated",
      "status": "passed"
    },
    {
      "artifact": "https://github.com/pcesar22/domes/pull/200",
      "command_or_observation": "Remote PR head equals local HEAD at 876fdd8b40f22175341671bff1d303d956376ebf, descends from pinned base 3b62a6c82160d0271b276bb42894e3d3bb69761e, and `git push origin HEAD` reported everything up to date.",
      "level": "automated",
      "status": "passed"
    },
    {
      "artifact": "https://github.com/pcesar22/domes/pull/200/checks",
      "command_or_observation": "Controller-owned exact-head CI polling after worker return.",
      "level": "automated",
      "status": "pending"
    },
    {
      "artifact": null,
      "command_or_observation": "No device command was authorized or executed.",
      "level": "accepted_command",
      "status": "not_applicable"
    },
    {
      "artifact": null,
      "command_or_observation": "Two-NFF reflash and complete readiness remain pending separate authorization, including audible maximum tones, peripheral-active self-test, stable current/minimum/largest-block internal headroom, and audio task stack high-water evidence on both boards.",
      "level": "physical",
      "status": "pending"
    }
  ]
}
```

</details>

**Comment by pcesar22** [comment]
Coordinator reconciliation of the 01:22 UTC repair handoff: numerical DIRAM/IRAM/image/partition sizes and fresh image/ELF/config hashes are now retained in the structured worker evidence and PR #200 without changing source head 876fdd8b40f22175341671bff1d303d956376ebf. All eight CI checks still pass on that unchanged exact head. The worker again reports pending controller CI and separately excluded physical readiness; neither is a new implementation failure. Route to fresh independent judgment of the retained-size remedy, not software acceptance. Preserve both build manifests as distinct builds; do not substitute the new binary hashes into old physical evidence. Physical operations remain unauthorized. The app worker still owns the active finite cycle: do not launch another controller until it exits.

**Comment by pcesar22** [comment]
Agent control-plane transition (judge)

Independent judge verdict: **approve**; criteria reviewed: 7; required rework items: 0.

Specification revision: `3b62a6c82160d0271b276bb42894e3d3bb69761e`
Raw session output is intentionally excluded.

<details><summary>Schema-validated handoff</summary>

```json
{
  "claim_boundary": "Approval covers source correctness, scope, focused host regression evidence, and fresh isolated build readiness for commit 876fdd8b40f22175341671bff1d303d956376ebf. It does not establish physical NFF headroom, peripheral behavior, or readiness exit. Exact-head CI remains the controller-owned post-judgment stage and was pending, with no known failure supplied.",
  "commit": "876fdd8b40f22175341671bff1d303d956376ebf",
  "criteria": [
    {
      "criterion": "Implementation is based on the pinned specification revision and remains within authorized scope.",
      "evidence": [
        "The reviewed commit descends directly from 3b62a6c82160d0271b276bb42894e3d3bb69761e.",
        "The diff changes only five allowed architectural surfaces: the audio service/driver, focused host test registration and implementation, and the NFF memory-repair plan.",
        "No protocol, partition, controller, dependency, device-operation, or issue-106 timing changes are present."
      ],
      "status": "met"
    },
    {
      "criterion": "Allocation attribution and before/after accounting are tied to the physical-NFF source/profile and distinguish measurements from analysis and hypotheses.",
      "evidence": [
        "docs/plans/nff-internal-memory-repair.md records the retained September 5 measurements and original application/ELF identities as historical inputs, explicitly not new measurements.",
        "The accounting covers the 32000-byte internal tone allocation, audio and profiler stacks, I2S DMA/scaling storage, trace allocations, and profiler static storage with capability and lifetime qualifications.",
        "The repair replaces the persistent 32000-byte internal allocation with a 512-byte statically owned chunk, predicting a 31488-byte reduction while clearly identifying physical headroom as unproven."
      ],
      "status": "met"
    },
    {
      "criterion": "The selected repair accounts for allocator capabilities, ownership, failure, fragmentation, copying, and bounded timing without changing functional tone behavior.",
      "evidence": [
        "AudioToneWriter uses a single service-owned 256-sample buffer and performs no runtime allocation.",
        "IAudioDriver::write is synchronous, and the production MAX98357A implementation copies/scales each chunk into driver-local storage before the call returns.",
        "Generation is capped at 16000 samples and 63 writes; phase and global fade indexing are preserved across chunks.",
        "Driver errors propagate immediately and successful partial writes fail closed."
      ],
      "status": "met"
    },
    {
      "criterion": "Focused regression tests exercise bounded generation/copying, lifecycle-relevant behavior, errors, and unchanged output.",
      "evidence": [
        "Six new tests cover the one-second chunk/write bound, exact equivalence to the legacy waveform, overlong duration capping, short-tone behavior, driver-error propagation, and partial-write rejection.",
        "A compile-time assertion fixes AudioToneWriter storage at 512 bytes.",
        "The retained handoff reports 339/339 host firmware tests passing at the reviewed commit."
      ],
      "status": "met"
    },
    {
      "criterion": "Memory thresholds, OTA/self-test protection, and peripheral capabilities remain unchanged.",
      "evidence": [
        "The diff does not modify the firmware 30 KiB internal-capability checks or the CLI 16 KiB health floor.",
        "Audio feature gating, asset playback, driver start/stop sequencing, and the post-write settling delay remain present.",
        "No capability or readiness check is disabled or relaxed."
      ],
      "status": "met"
    },
    {
      "criterion": "A fresh isolated physical-NFF image was built with pinned ESP-IDF provenance and retained identity/size evidence.",
      "evidence": [
        "The handoff records an ESP-IDF v5.4.4 physical_nff build using an isolated build directory and SDKCONFIG.",
        "Retained identities are domes.bin SHA256 8837169017c7a9b032c8e3bdb6fb130ee26116ddae4749db3edeae28811d3e24, domes.elf SHA256 8d217dbed8f1993e78d7787b9c9078775306c489d2f46e7592a7f55d5f47a0fd, and SDKCONFIG SHA256 5b26571b1387b69ab0610462b58e928883c8c21ba5998a541db4e2bec2a9bf17.",
        "The retained size evidence reports a 1486128-byte binary and 480976 bytes free in the smallest application partition."
      ],
      "status": "met"
    },
    {
      "criterion": "The PR discloses the remaining separately authorized physical acceptance check without claiming physical completion.",
      "evidence": [
        "PR #200 is identified as targeting the reviewed exact head 876fdd8b40f22175341671bff1d303d956376ebf.",
        "The retained evidence explicitly leaves two-NFF reflash, peripheral-active self-test, audible-tone checks, stable current/minimum/largest-block headroom, and stack high-water evidence pending separate authorization.",
        "No device access or physical-validation claim was made."
      ],
      "status": "met"
    }
  ],
  "issue": 198,
  "pull_request": 200,
  "required_rework": [],
  "spec_revision": "3b62a6c82160d0271b276bb42894e3d3bb69761e",
  "verdict": "approve"
}
```

</details>

**Comment by pcesar22** [comment]
Agent control-plane transition (verification-worker)

Verification state: **human_review**; checks: 9; repairs: 0; blockers: 0.

Specification revision: `3b62a6c82160d0271b276bb42894e3d3bb69761e`
Raw session output is intentionally excluded.

<details><summary>Schema-validated handoff</summary>

```json
{
  "blockers": [],
  "checks": [
    {
      "name": "Independent judge approval",
      "status": "passed",
      "url": "https://github.com/pcesar22/domes/issues/198#issuecomment-5548549998"
    },
    {
      "name": "Build ESP32-S3 Firmware",
      "status": "passed",
      "url": "https://github.com/pcesar22/domes/actions/runs/33934639219/job/<redacted-device-id>"
    },
    {
      "name": "Execute ESP32-S3 QEMU Runtime",
      "status": "passed",
      "url": "https://github.com/pcesar22/domes/actions/runs/33934639219/job/<redacted-device-id>"
    },
    {
      "name": "Run Unit Tests",
      "status": "passed",
      "url": "https://github.com/pcesar22/domes/actions/runs/33934639219/job/<redacted-device-id>"
    },
    {
      "name": "Build CLI Tool",
      "status": "passed",
      "url": "https://github.com/pcesar22/domes/actions/runs/33934639219/job/<redacted-device-id>"
    },
    {
      "name": "Test Host Tooling",
      "status": "passed",
      "url": "https://github.com/pcesar22/domes/actions/runs/33934639219/job/<redacted-device-id>"
    },
    {
      "name": "Flutter / Analyze And Test Flutter App",
      "status": "passed",
      "url": "https://github.com/pcesar22/domes/actions/runs/33934639219/job/<redacted-device-id>"
    },
    {
      "name": "Flutter / Build iOS App",
      "status": "passed",
      "url": "https://github.com/pcesar22/domes/actions/runs/33934639219/job/<redacted-device-id>"
    },
    {
      "name": "CI Gate",
      "status": "passed",
      "url": "https://github.com/pcesar22/domes/actions/runs/33934639219/job/<redacted-device-id>"
    }
  ],
  "commit": "876fdd8b40f22175341671bff1d303d956376ebf",
  "issue": 198,
  "pull_request": 200,
  "repairs": [],
  "spec_revision": "3b62a6c82160d0271b276bb42894e3d3bb69761e",
  "state": "human_review"
}
```

</details>
